### ISSUE TITLE
South Africa openspending api

### ISSUE THREAD

**Issue by steveoni** [datopian/client-gift-api-work#2]
We want to add old south Africa opendspending API for all south Africa datasets into the new API 

## Acceptance
- [ ] Ensure all south Africa dataset API are present in the new API

## Task

- [ ] fetch old south Africa dataset from migrated openspending google bucket
- [ ] Mitigate new data fetched with the current pipeline
- [ ] Generate api for each of the dataset

**Comment by SusanBot85** [comment]
@steveoni could you please add an estimate in terms of how long you think the above would take

**Comment by SusanBot85** [comment]
CODING: 8 h
GENERATING API: 3 DAYS (Depending on size of datasets this is a rough estimate and might be adjusted once all the data has been investigated)

CoB 31 March 2022 Thursday
